### ISSUE TITLE
keyTap sometimes doesn't apply modifier(s)

### ISSUE THREAD

**Issue by ligustah** [octalmage/robotjs#143]
As I mentioned in #141 I have been trying to reliably reproduce another issue I found, but I think it is somehow related to timing. I'm still using a program to show keystrokes and I created a small script that would press all keys from F1 to F12, all with 'control' set as the only modifier.

Most of the time it would show "Ctrl + F1" pressed, for example. However, sometimes it would first show "Ctrl" and then "F1" very shortly after, actually pressing the keys in succession rather than in combination.

I'll see if I can somehow produce a reliable PoC.

**Comment by ligustah** [comment]
From my tests it seems that it always works when I use keyToggle to "manually" tap the keys.

**Comment by octalmage** [comment]
Hmm, interesting. Is is on Windows right? I can't seem to reproduce it on Mac. 

Does it help to increase [setKeyboardDelay](https://github.com/octalmage/robotjs/wiki/Syntax#setkeyboarddelayms)?

**Comment by ligustah** [comment]
Windows 10

I'll test with the keyboard delay and will report here. Given that this seems to be a timing issue, that one might actually solve the problem.

**Comment by octalmage** [comment]
Thanks! I suspect that it might help. I've ran into similar issues on Mac where it just can't handle events that fast.

**Comment by ligustah** [comment]
So I finally found some time to get back to this. I tried changing the keyboard delay to no avail though (tried up to 1000ms).

This is the code that I used to test this along with a tool called KeyPosé: https://gist.github.com/ligustah/869a4f03b2f8ae01b9a0

It taps the keys in succession most of the time now (tested against 0.3.6, because I cannot currently compile the most recent version).

**Comment by ScriptPup** [comment]
I have the same issue  I believe. I was noticing that when I was trying to fire c+control it worked about 60% of the time, the other 40% it typed a C. I'm firing the control+c when I send control+g (building an clipboard extension)

Additional testing and I figured out that if "roll" my tap so that I release the control key too quickly, then it types the C, otherwise it fires correctly if I hold the CTL key down and don't release it.

Though @ligustah doesn't seem to be fiding from a keystroke, so maybe it's a slightly different issue?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
