### ISSUE TITLE
Test Utility

### ISSUE THREAD

**Issue by Deltatiger** [octalmage/robotjs#154]
Should we have some kind of test utility that will perform the basic functionality testing automatically. This could reduce the roll-out time considerably. Also if we can make the utility multi-platform then it would be even better.

I was thinking of something like a Python Script with Tkinter UI to test all the UI commands. This utility can sense lot of the system settings and generate a RobotJS script to test it out.

**Comment by octalmage** [comment]
This is what I was talking about in #98. I got something working in the keyboard-tests branch using only the terminal, but it won't work for TravisCI or Appveyor. So I started work on a new application using Electron that will be cross platform, and do what we need. With TravisCI we can test Mac OS X and Linux, and with Appveyor we can test Windows automatically. The goal is to eventually use these services to test/build RobotJS then upload the builds to S3 for pre-node-gyp. 

I also spent some time during the week improving our tests and error handling, about to merge my changes here: #155. 

Anyway, to me Electron seems like a good choice since it's Node.js.

**Comment by octalmage** [comment]
I started work on this today! So far it's an Electron app that you run using child_process.spawn and it reports events using stdout. Seems to work well. When it first opens it sends a ready event with the absolute location of all of the elements (buttons, inputs) on the screen so the test can easily find the input it needs. I'm going to create a library you we'll include in RobotJS to make using it easier. 

I'm going to try to get something uploaded today.

**Comment by octalmage** [comment]
Here it is:

https://github.com/octalmage/targetpractice

I'm very excited to use this to help test RobotJS.
