### ISSUE TITLE
[Question] Distributing

### ISSUE THREAD

**Issue by SamuraiJack** [octalmage/robotjs#189]
Hello,

If I've installed RobotJS on my machine (ubuntu 14) and then will just zip the whole folder with my project (including "node_modules") - would that mean that it will work on other ubuntu machines?
Same question about Windows machine.

Is it possible to create a "static" build of RobotJS, which will not require any dependencies to work on selected platform?

I'd like to distribute RobotJS along with my application and not sure if it requires some special installation.

Regards, Nickolay

**Comment by octalmage** [comment]
Hi @SamuraiJack! 

Correct, distributing RobotJS by including the node_modules directory will work for the platform it was compiled on. Windows, Mac, or Linux. The user won't have to have dev tools installed. Now if you're not distributing Node (using Electron or NW.js), they'll most likely have to compile RobotJS on their own because of different Node versions and architectures (32/64bit). That said, compiling RobotJS shouldn't be necessary anymore, running `npm install` will download the correct binary from the Github releases: 

https://github.com/octalmage/robotjs/releases/tag/v0.4.2

Hope this helps!

**Comment by SamuraiJack** [comment]
Cool! I guess I'll just give it a try. Thank you for the help and this excellent project!

**Comment by octalmage** [comment]
No problem! Let me know if you need anything else.
