### ISSUE TITLE
How to save screen.capture.image as a png image

### ISSUE THREAD

**Issue by IChocolateKapa** [octalmage/robotjs#222]
RT

**Comment by demipixel** [comment]
Googled "save buffer as png node.js"

First three things that came up:

http://stackoverflow.com/questions/6926016/nodejs-saving-a-base64-encoded-image-to-disk
> My Express app is receiving a base64-encoded PNG from the browser (generated ..... Right answer -> Create and save buffer image node.js fs.

Eh, maybe.

http://stackoverflow.com/questions/20267939/nodejs-write-base64-image-file
> My NodeJS-Server receives a picture base64 encoded. ... Then you can save the buffer using your above method. fs. ... Thanks for this Julian, I noticed you are putting in a png base64 string and outputting a jpg. Does that ..

Looks good.

https://www.npmjs.com/package/png
> A C++ module for node-js that converts an RGB and RGBA buffers to PNG images ... You can either send the png_image to the browser, or write to a file, or do ...

Description says it all.

**Comment by IChocolateKapa** [comment]
@demipixel ，I tried the simplest code as following, but it didn't work, could you successfully save it as a picture?

    var img = robot.screen.capture(0, 0)；
    fs.writeFile('output.png',  img.image)；

**Comment by octalmage** [comment]
This is in the works. The image returned from screen.capture contains more than just the image, so just writing it to a file won't work as expected. Soon there will be a function to save it though.

**Comment by octalmage** [comment]
You can use the code here: 

https://github.com/octalmage/robotjs/pull/191

**Comment by Disorrder** [comment]
anyway, how can I get image data from buffer?

**Comment by LazyFatArrow** [comment]
is this solved ?

**Comment by tarunjuneja** [comment]
Can someone post information regarding how can i split images in the buffer so that i can save them individually?

Is there any indication in the buffer which i can use to understand its the end of a image.

**Comment by developer239** [comment]
```
Googled "save buffer as png node.js"

First three things that came up:

http://stackoverflow.com/questions/6926016/nodejs-saving-a-base64-encoded-image-to-disk

My Express app is receiving a base64-encoded PNG from the browser (generated ..... Right answer -> Create and save buffer image node.js fs.
Eh, maybe.

http://stackoverflow.com/questions/20267939/nodejs-write-base64-image-file

My NodeJS-Server receives a picture base64 encoded. ... Then you can save the buffer using your above method. fs. ... Thanks for this Julian, I noticed you are putting in a png base64 string and outputting a jpg. Does that ..
**Maybe again**.

https://www.npmjs.com/package/png

A C++ module for node-js that converts an RGB and RGBA buffers to PNG images ... You can either send the png_image to the browser, or write to a file, or do ...
Perfect
```

Hmm..

https://github.com/pkrumins/node-png/graphs/contributors

... last commits be like 7 years ago, 4 years ago, 7 years ago ... when I try to install it it fails ... 

... when I look at the issues: `Cannot build under Windows 10 - node 0.12.7 - node-gyp 3.3.1` `cannot build under nodejs v4.1.2 with node-gyp v3.0.3` `Unable to run any example from the examples folder` `node-gyp build fails with io.js` `Fails to build` 

**Maybe again?**

```
This is in the works. The image returned from screen.capture contains more than just the image, so just writing it to a file won't work as expected. Soon there will be a function to save it though.
```

Why don't you write at least basic documentation? What is that object? What can it do? Why use it? What type of buffer is it? How do I work with it? So many questions.

My answer in documentation?

```
image | The raw image (buffer).
```

![](https://cdn.meme.am/cache/images/folder381/600x600/12235381/facepalm-polar-bear.jpg)

Now I know this is opensource. I am expecting comments like:

"This is free we have no obligation to make it work."
or maybe
"Buffer. Everyone should know what buffer is."
or
"UTFG."

Why? Why not spend 5 more minutes. Literally 5 more minutes. You can link documentation to

* how does buffer object look like in javascript
* how to use buffer object in javascript
* why use buffer object instead of something else

 You don't even have to write the documentation. But the fact that you don't do that. The fact that you are being rude and when someone asks you a question you try to show them how to use the google !! WITH EXAMPLES THAT DO NOT EVEN WORK !! makes me really sad.

![](https://cdn.meme.am/cache/images/folder490/600x600/11655490/sad-panda-south-park.jpg)

I just spend an hour trying to save use the buffer and save it to file.


I failed.

I will admit that I have no sufficient knowledge. Obviously I do not have. I do webs. I know php. I know symphony. I know laravel. I know some javascript. I know react. I know some other stuff. I do not know how to work with image buffers because I did not have to.

One day I found out about this amazing library. I created a simple color bot !! you did a fucking great work actually. I was sooo hapy.


![](https://img.memesuper.com/a07762b6b80aed1aa9762572b98a3a27_south-park-craig-meme-generator-imgflip-craig-meme-south-park_480-358.jpeg)

Then I was like. Wow. This is actually pretty cool. How about making image recognition and make the bot even better? What a great idea? Yes? **No!**

You do not support template matching that is ok. I spent few hours learning about template matching and created a working example with another library. I spent a lot of time doing that. Then I was like. Great! Now it is time to make the template matching useful.

Two hours later I am writing this rant because I did not know how to make it work.

I really don't.

Your documentation tells me that I have the raw image. But I just don't know how to use it.

If I knew that I have to know how to work with fucking buffers. I would learn something about buffers before trying to use your library. But I did not know that. What a mistake. Oh wait it is my fault because this is open source library. You have only 6 000 stars. I should have known that you have a crappy documentation.

Sorry. I will contineu my quest learning about image buffers. And when I am done I will make a pull request because you know. It might help some stupid people who don't know how to work with buffers.

![](http://i.cdn.turner.com/v5cache/CARTOON/site/Images/i21/at_righteousquest_300x165.jpg)

**Comment by developer239** [comment]
LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL

` image: any`

So much for using typescript. This is getting better and better.

**Comment by developer239** [comment]
In the end I got two solutions working

1) Does not have correct colors. I don't know why. I don't want to know why. Just ... fuuuuuuuuck ...

```
let image = new Jimp(size, size, function(err, img) {
  img.bitmap.data = rimg.image;
  img.getBuffer(Jimp.MIME_PNG, (err, png) => {
    console.log(png)
    image.write(path, resolve);
  });
});
```

2) This one has correct colors but is obviously way too slow for real world usage. Using shelljs is literally milion times faster for larger images.

```
let jimg = new Jimp(size, size);
for (var x=0; x<size; x++) {
        for (var y=0; y<size; y++) {
                // hex is a string, rrggbb format
                var hex = rimg.colorAt(x, y);
                // Jimp expects an Int, with RGBA data,
                // so add FF as 'full opaque' to RGB color
                var num = parseInt(hex+"ff", 16)
                // Set pixel manually
                jimg.setPixelColor(num, x, y);
        }
    }
jimg.write(path)
```

My quest has ended. Enjoy your life.

**PLEASE REMOVE THIS FUNCTIONALITY FROM YOUR DOCUMENTATION BECAUSE IT IS HIGLY MISLEADING. I JUST WASTED TWO DAYS OF MY LIFE BECAUSE OF THIS SHIT.**

**Comment by developer239** [comment]
![](http://creepygift.com/wp-content/uploads/creepy-added-shit-perfume.png)

**Comment by Disorrder** [comment]
@developer239 at first, you spammed to all participants. 2nd is it's just your job, to fight with any issue you find writing your code. Of course, that two days may be wasn't good at all, but you got some experience of what Buffer is and smth like that. If you need another functionality, just have a look for another libs (at least, i found `robot-js` with similar screen capturing).
Watching your code I see you're did not understand how buffer works anyway.
Please be correct a little more.

**Comment by octalmage** [comment]
That user has been blocked. The documentation does not mention saving a screen capture to a file, since it's currently not possible (or implemented). As always, I'm happy to accept PRs or collaborate. I'm extremely busy with work and screenshot saving isn't something I have a need for.

**Comment by voteTrump2020** [comment]
I really appreciate the work you did. You probably don't realize it but thanks to this library I got a glance on a whole new world of programming in nodejs.

Controlling mouse and keyboard on desktop? Compiling javascript application with electron in order to make the application native? That is s cool.


But look again at the text that you just wrote:

`The documentation does not mention saving a screen capture to a file, since it's currently not possible (or implemented)`

Pleasy, one more time:


`The documentation does not mention saving a screen capture to a file, since it's currently not possible (or implemented)`

**it's currently not possible**

You should always keep in mind that when you publish something and when it gets popular many people will try to use it. Some of them will have stupid questions. Other people will not know whether they have stupid questions or whether the library they are trying to use is stupid.

I had no idea how to use buffers in nodejs. There was no way that I could figure out why my code does not work. Why using `fs` does not work. Why bunch of other libraries do not work. Why using `jimp` does not work - well it saved the file but it had different colors so it was useless.

When you have a kid one day. When you give your kid RC Car or some similar toy. Don't forget to give the kid batteries too because hey ... I know that it is free. I know that you don't really have to give anything to your kids. But you know if you give them something make sure it works. Otherwise they might spent whole weekend crying over the freaking car thinking that they broke it.

Kindly please, remove the option to make the screenshot from the documentation because as you said yourselve **it's currently not possible** to use it.

**Comment by voteTrump2020** [comment]
Read some articles about open source vs commercial software. Best example for all of them is amazon that successfully killed many open source platforms. Why? Because

_most of the open source libraries do not freaking work and when users get frustrated contributors to that library just say that it is open source and they don't have enough time so it is ok that the library is broke._

If it does not work. Take it down. It is that simple.

If there is a future that does not work and you don't know how to fix it? Take it down.

Why you ask? Imagine that you want to learn something. You know how the reality looks like these days? Before you can learn programming - or whatever - you actually need to learn how to look up the information. There is so much information noise. I mean so freaking much.

For every 1 library written in javascript there are 10 other that are either outdated or not working. Great example from javascrpt is apollo graphql. There were so many changes. I spent many days (actual man days) trying various different tutorials that were supposed to teach me something about graphql. Guess what? They were all outdated. All of them. In the end I created my own apollo react redux graphql repository because I just couldn't find any working example.

I am not the one killing the open source community. You are.With your information noise. If I wanted to control mouse and keyboard I could just use `shelljs` or something and write a library in one afternoon. Three methods like `mouse.move()` `keyboard.type()` `keyboard.pressKey()`. I saw that your library also allows me to work with computer screen. Getting colors. Taking screenshots. So I decided to use it.

I am not the only one who was trying to make it work. Imagine how many people did not even complain because they did not want to sound stupid or did not want to be rude. So many wasted afternoons.

F**k me. I don't matter. You are killing the open source community. The first thing that I do these days when trying something new is `git clone` `npm install` and `node-gyp build`. Because I don't trust ANY repository anymore. And I am not the only one. There are actually articles about people who do not use 3rd party libraries at all. There are articles that say that it is a good convention not to use 3rd party library just to save few lines of code if you can make something work yourself. Do you know why? Because people don't trust it anymore.

**Comment by Disorrder** [comment]
@voteTrump2020 nice name lol.
Well, it's open source, so may be you can fix it? Make PR for it. I think, most of us are busy on their job, so this feature is not popular, but may useful for someone else, thats why no need to delete this code.
Still can't believe developers like you are alive -_-

**Comment by octalmage** [comment]
Sorry guys, I've deleted the comments and reported the user to GitHub.

**Comment by octalmage** [comment]
I'm going to lock and close this issue, I don't plan on implementing screen saving in the near future, going to focus on bugs and getting the existing functionality working as expected. This project needs collaborators, anyone interesting in helping please reach out to me. 

Any questions about screen saving or capturing should go in #13.

Thanks!
