### ISSUE TITLE
Mouse lagg on windows

### ISSUE THREAD

**Issue by Skeukry** [octalmage/robotjs#241]
I noticed my mouse (with touchpad) lagging every few seconds on windows 10 a day after I installed this module. I would like to know if it's possible that it installed something or ran something that may persist even after npm uninstall.
I never ran the module, so only the installition itself could cause the problem, otherwise it's something else.

**Comment by Deltatiger** [comment]
I am not familiar with something like this being caused by installing a node module.
Did you install anything else in the recent past ? 
As far as this module is concerned a npm install would not go as far as messing up your drivers.
I would suggest a system reboot ( this helps clear up memory corruptions and in memory problems ). If that does not help then probably driver re-installation or update (?).
Also does it work well when a physical mouse is attached ?

**Comment by Skeukry** [comment]
It only happens with the touchpad actually and I already tried those methods. I don't really think the module may be the problem myself, but there's nothing else I downloaded or changed lately, so I thought maybe some default library was overwritten or a registry changed or something. If not then sorry for bothering, maybe just a windows update messed it up. :)

**Comment by octalmage** [comment]
Hi @Skeukry, 

Sorry you're having issues! As @Deltatiger tiger mentioned RobotJS us only downloaded, it doesn't match any changes to the underlying os. 

If you need anything else please let us know!
