### ISSUE TITLE
Can't robot.typeString() from Windows service

### ISSUE THREAD

**Issue by charlesread** [octalmage/robotjs#269]
Good day,

I have a small app that I installed as a service on Windows 10 using NSSM, the app itself is working just fine, but `robotjs` isn't `typeString`ing from the app when it is run as a service.  Any way around this?

Thanks!

**Comment by relsqui** [comment]
I had this problem from a standalone script not running as a service, and switching to `typeStringDelayed` seemed to help. (Adding a pause between clicking on an element and typing into it may also have helped, I did both at the same time.)

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.

**Comment by eddiefletchernz** [comment]
Did you ever solve this? 

I am trying to `robot.keyTap("audio_stop");` and `robot.keyTap("audio_play");` from within a Windows NSSM service. I have tried allowing it to interact with desktop, and also logging in as my own user account instead of `Local Service` but nothing seems to be working. The script runs but the audio does not stop and start.

Everything works fine if I run it from a CMD window but I would like my bot to run in the background as a service.

**Comment by eddiefletchernz** [comment]
Update, it appears that I get the same issues when running as a node-windows installed service, and even if I run it using a simple VBScript command to start without a window.

E.g. `run.vbs` -> `CreateObject("Wscript.Shell").Run "node index.js", 0`
