### ISSUE TITLE
Node 8 NPM

### ISSUE THREAD

**Issue by Bernkastel-0** [octalmage/robotjs#316]
## Expected Behavior

NPM should correctly install robotjs.

## Current Behavior

NPM does not correctly install robotjs with node 8.
http://i.imgur.com/efRGLNd.png

The exact same error had been encountered by 6 different machines running completely different networks and environment. Downgrading to node 7 solves the problem.

## Possible Solution

Make npm not point to a package version that doesn't actually exist in the repository.

## Steps to Reproduce (for bugs)

1. Install node 8.
2. npm install robotjs

## Your Environment

* RobotJS version: - unable to install
* Node.js version: 8.12 - 8.14
* npm version: Variable, all very recent
* Operating System: Win 10

**Comment by ssmak** [comment]
從我的 Samsung Galaxy 智能手機發送。


-------- 原始訊息 --------
由： Bernkastel-0 <notifications@github.com>
日期： 17/7/20 18:06 (GMT+08:00)
收件人： octalmage/robotjs <robotjs@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主題： [octalmage/robotjs] Node 8 NPM (#316)

Expected Behavior

NPM should correctly install robotjs.

Current Behavior

NPM does not correctly install robotjs with node 8.
http://i.imgur.com/efRGLNd.png

The exact same error had been encountered by 6 different machines running completely different networks. Downgrading to node 7 solves the problem.

Possible Solution

  *

Steps to Reproduce (for bugs)

  1.  Install node 8.
  2.  npm install robotjs

Context
Your Environment

  *   RobotJS version: - unable to install
  *   Node.js version: 8.12 - 8.14
  *   npm version: Variable, all very recent
  *   Operating System: Win 10

**Comment by roy2651** [comment]
I also install robotjs with node v 8.1.4 on my mac

**Comment by ChrissP92** [comment]
I have the same problem.

I tried modifying `package.json` of **robotjs** to force `prebuild-install` to get latest available version from here: https://github.com/octalmage/robotjs/releases/tag/v0.4.7
So I wrote:

```
"scripts" {
    "test": "node test/all.js",
    "install": "prebuild-install -t v5.1 || node-gyp rebuild"
}
```
I had also download library folder as ZIP and `npm link`ed to it, otherwise `npm install` hasn't bother with **-t** parameter.

I still cannot install library, but I got some other error:

> D:\app\tests\node>npm link ./node_modules/robotjs
> 
> > robotjs@0.4.7 install D:\app\tests\node\node_modules\robotjs
> > prebuild-install -t v5.1 || node-gyp rebuild
> 
> abi-target:  5.1
> prebuild-install info begin Prebuild-install version 2.3.0
> prebuild-install info install installing standalone, skipping download.
> 
> D:\app\tests\node\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Users\Krzycho\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\..\
> ..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Projekty w tym rozwiązaniu są tworzone po kolei. Abu umożliwić tworzenie równoległe, dodaj przełącznik "/m".
> MSBUILD : error MSB3428: Nie można załadować składnika Visual C++ "VCBuild.exe". Aby rozwiązać ten problem:1) zainstaluj zestaw .NET Framework 2.0 SDK, 2) zainstaluj program Microsoft Visual Studio 2005 lub 3) dodaj lokalizację skła
> dnika do ścieżki systemowej, jeżeli jest zainstalowana w jakiejś lokalizacji.  [D:\app\tests\node\node_modules\robotjs\build\binding.sln]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\Krzycho\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
> gyp ERR! stack     at emitTwo (events.js:125:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Krzycho\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd D:\app\tests\node\node_modules\robotjs
> gyp ERR! node -v v8.7.0
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! robotjs@0.4.7 install: `prebuild-install -t v5.1 || node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the robotjs@0.4.7 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Krzycho\AppData\Roaming\npm-cache\_logs\2017-10-15T00_13_23_483Z-debug.log

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
