### ISSUE TITLE
Wayland compatible

### ISSUE THREAD

**Issue by jukefr** [octalmage/robotjs#333]
Currently requires X to run on Linux,
Wayland is set on becoming the new standard for most distros in the near future, would be nice if this tool could be compatible with it.

**Comment by sixpetrov** [comment]
I think that's not possible, since wayland prevents sending kestrokes or mouse events to applications for security reasons.

And that is the main reason why I left Linux. If I can't control anything, what's the point.

**Comment by unfa** [comment]
@sixpetrov - I don't understand. Since when you can't control anything on Linux? You can use whatever desktop environment or window manager you want. Heck! If you don't like something you can *fork* them! Is there any other operating system that gives it's users that amount of control over it?

Wayland chose to prevent that functionality to increase user security - I guess I won't use it then, because I prefer the possibilities of desktop automation of X11.

But nobody will force any of us to use Wayland or X11 or whatever. Wayland is there to fix some problems with X.org, but X.org is not going to be banned or cast out or broken - they will exist together. And right now X11 is still the standard.

**Comment by sixpetrov** [comment]
@unfa man I would really like to just use X11 and don't care about wayland. But my biggest concern is hardware. What if at some point nvidia stops supporting X11 completely? I don't have time to deal with open source drivers and I certainly don't wan't to use on-board graphics. 

Next problem is gtk3 and new QT5, they don't support all automation tools. Sending keystrokes to these apps is limited. I use space as modifier, but that didn't work in new apps. So I was forced to use gtk2, qt4 or java apps.

Believe me I miss Linux every single day, but without all my tools I can't work properly...

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
