### ISSUE TITLE
mouseClick on div in browser

### ISSUE THREAD

**Issue by reznikGit** [octalmage/robotjs#388]
Hi, can i click on div in browser? I want something like this
`mouseClick(document.querySelector(.btn))`

**Comment by Deltatiger** [comment]
RobotJS is used for UI automation, which means that it automates your mouse over your full desktop. It does not have access to the other programs (like browser) data. It can control the mouse and keyboard over your entire screen.
So it cannot be used perform actions like clicking on the DOM nodes, since it does not even know what a DOM is.

I would suggest selenium for browser related automation (I assume that is what you are targeting).
