### ISSUE TITLE
OSX El Captain compatibility issue

### ISSUE THREAD

**Issue by matteocrippa** [octalmage/robotjs#39]
It seems that using OS X El Captain beta the mouse move doesn't work, mouse get is pretty working well

If you need any log, feel free to ask

**Comment by octalmage** [comment]
Hey! Sorry for the delay. I probably won't be able to look into this until I update my Mac, and I'm afraid to do this if it's going to break RobotJS. I'll see if I can get a VM going when I have time. 

Thanks for the report!

**Comment by octalmage** [comment]
Is there an error message or does the mouse just not move? 

Are you running the OS in a VM or native? 

Also if anyone else is running OS X El Captain could you confirm if you have the same issue?

**Comment by matteocrippa** [comment]
I was running it on a native mac, so not VM.
But I can't help you anymore, I was forced to revert to 10.10

**Comment by dkrutsko** [comment]
I got the latest version of El Captain running, it turns out that there is some problem with [CGEventCreateMouseEvent](https://developer.apple.com/library/mac/documentation/Carbon/Reference/QuartzEventServicesRef/#//apple_ref/c/func/CGEventCreateMouseEvent), I'm in the process of figuring it out, will post when I find out more. It appears the mouse move is the only function having problems.

**Comment by octalmage** [comment]
I'm going to close this, there aren't any incompatibilities with El Captain at the moment.
