### ISSUE TITLE
screen shot not saving to file

### ISSUE THREAD

**Issue by pg07codes** [octalmage/robotjs#438]
## Expected Behavior
function snapshot(){
        
        let imgData = robot.screen.capture()
        let imgBuffer=imgData.image
        console.log(imgBuffer)
        fs.writeFile('snapshot.png', imgBuffer, (err) => {
            if (err) throw err; // no error here
            console.log('The file has been saved!');
        });
    }

## Current Behavior
after the file is saved, when i open it : ERROR comes ` unsupported file format`

## Possible Solution
no idea.

## Steps to Reproduce (for bugs)
use the above code to click and save screen shot.

## Your Environment
* RobotJS version: latest
* Node.js version:8.9.3
* Operating System: windows 10

**Comment by Deltatiger** [comment]
The output from the capture function is a raw image. That means it is a pixel grid (array or arrays) where each pixel consists of the 3 colors (RGB).
This is not directly recognized as an image because the format is different.
The simplest way would be to convert it to a BMP (Adding more headers before writing the contents of the file).

**Comment by pg07codes** [comment]
ok. thanks.
