### ISSUE TITLE
Alt-Tab is not working on Windows Server 2012 (in virtual environment)

### ISSUE THREAD

**Issue by Alex0007** [octalmage/robotjs#492]
Alt-Tab is working on my machine with Windows 10, but not working on Windows Server 2012 which is running in something like virtualbox. 

## Your Environment

* RobotJS version: 0.5.1
* Node.js version: v10
* npm version:
* Operating System: Windows Server 2012 (in virtualbox possibly)

```js
        robot.keyTap("tab", "alt"); // nothing happens
        robot.keyTap("tab"); // this works
```

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.

**Comment by Sentero-esp12** [comment]
I have the same problem on Linux Mint Cinnamon (Linux 5.0.0-32-generic x86_64). Should this be reopened or should I create a new issue (because the problem is on Linux)? If I install from npm, `alt-tab` works, but not if I download from GitHub and install from folder (this version is necessary for my app since it fixes keystroke delays).
