### ISSUE TITLE
Shift case not working in Linux

### ISSUE THREAD

**Issue by jekku** [octalmage/robotjs#81]
I was planning to do a "Coding ghost" showcase which automagically recreates code in sublime given a directory of a code base.

It seems like 
```js
robot.typeString("~!@#$%^&*()_+");
```

Outputs : 
```
`12345678()-=
```

You can checkout 

https://github.com/jekku/creeper/tree/issue_link/no_shifts_unix

**Comment by mccxiv** [comment]
I was about to post a new issue, then saw this one.

I'm having the same exact problem on Windows 8.1.
Anyone savvy enough to understand what's going on?

**Comment by jekku** [comment]
up up up

**Comment by Deltatiger** [comment]
I can't even get robotjs to install in linux ;/ Some problem with nan 1.3.0 ( or 1.3.1 ). Will have to look into it more.

**Comment by koustuvsinha** [comment]
yes trying to print ! will output 1 in linux..

**Comment by jekku** [comment]
@octalmage Anyonne still maintaining robot.js?

**Comment by aequasi** [comment]
@jekku Yes, he is.

**Comment by geekoftheweek** [comment]
I'm having the same issue on Windows 10.

**Comment by Deltatiger** [comment]
@geekoftheweek I just got robotjs to install on Ubuntu 12.04. Will check the issue there and then move to Windows 10. ETA 2 days.

**Comment by octalmage** [comment]
Sorry guys, big project at work. Will test this when I have time.

**Comment by Deltatiger** [comment]
Can anyone confirm if the reverse ever happens ? When you use ``` robotjs.typeString("123")``` and get ```!@#```. Just curious.

The problem is that all keys are sent as keyboard input signals. So just like when you type !@# you need to hold down shift. That is not being handled as of yet. This is the case for characters !@#$%^&* (i.e. From 1-8). This fix wont be pretty or easy. I am currently working on this. And this problem is not limited to Ubuntu. I have confirmed this in windows 7 also. I am guessing this is universal.

**Comment by octalmage** [comment]
Yeah that's messy, thanks for looking into this @Deltatiger! For now using `keyTap` is a good workaround. For example: 

```
robot.keyTap("1", "shift");
```

**Comment by octalmage** [comment]
Also @Deltatiger, I tested `robot.typeString("123");` in Ubuntu and it works as expected.

**Comment by jekku** [comment]
Alright then. Just inform us in the version bump when it gets fixed will do the shift for now :)
