### ISSUE TITLE
scrollMouse doesn't work on Windows XP.

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#97]
See #50. I commented the code out in 062be3f6fc249e42dbcbfdc6aa6f996cd3725274 until we can figure it out. 

cc: @Deltatiger

**Comment by verth** [comment]
I was able to reproduce your errors in [#50](https://github.com/octalmage/robotjs/pull/50) on Windows 10.

The problem is VS2008 (or more specific C89), which requires variables to be declared at the beginning of a scope. Newer versions of VS have better support for C99, with ex. better variable declarations.

I could resolve this by putting the declaration of mouseScrollInput at the beginning of the scrollMouse function, alternative you could also wrap the Windows-elif in an enclosing {} block.

**Comment by octalmage** [comment]
@verth Thanks for looking into this! Could you submit a pull request? I'm fine with moving the variables to the top of the function.

**Comment by verth** [comment]
Yes, I will! Wasn't too sure what you would prefer. Will look to do it today or tomorrow.

**Comment by octalmage** [comment]
This was resolved by #163.
